server:
  port: 7001
  servlet:
    context-path: /api/coes
  error:
    include-message: ALWAYS
spring:
  cloud:
    nacos:
      discovery:
        server-addr:
  application:
    name: coesplus-coes
  datasource:
    username:
    password:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      mysql:
        usePingMethod: false
#  shardingsphere:
#    datasource:
#      names:
#        master,slave
#      master:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url:
#        username:
#        password:
#      slave:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url:
#        username:
#        password:
#    masterslave:
#      load-balance-algorithm-type: round_robin
#      name: dataSource
#      master-data-source-name: master
#      slave-data-source-names: slave
#    props:
#      sql:
#        show: true
  redis:
    host:
    port:
    database:
    password:
  mail:
    host:
    port:
    username:
    password:
    default-encoding: UTF-8
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 20MB
      file-size-threshold: 20MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:logback-spring.xml

minio:
  endpoint:
  accessKey:
  secretKey:
  bucketName: