version: "3.2"

services:
  ngnix:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
      - 7070:7070
      - 7080:7080
    privileged: true
    volumes:
      - /root/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /root/nginx/logs:/var/log/nginx
      - /root/nginx/html:/usr/share/nginx/html

