// import { h } from 'vue';

export const columns = [
  {
    title: 'ID',
    key: 'id',
    edit: false,
    width: 150,
    align: 'center',
  },
  {
    title: '课程名称',
    key: 'name',
    editComponent: 'NInput',
    edit: true,
    width: 150,
    align: 'center',
  },
  {
    title: '学院',
    key: 'facultyName',
    editComponent: 'NInput',
    edit: true,
    width: 100,
    align: 'center',
  },
  {
    title: '任课老师',
    key: 'teacherName',
    editComponent: 'NInput',
    edit: true,
    width: 130,
    align: 'center',
  },
  {
    title: '课室',
    key: 'classroom',
    editComponent: 'NInput',
    edit: true,
    width: 70,
    align: 'center',
  },
  {
    title: '开始时间',
    key: 'startTime',
    editComponent: 'NInput',
    edit: true,
    width: 100,
    align: 'center',
  },
  {
    title: '结束时间',
    key: 'endTime',
    editComponent: 'NInput',
    edit: true,
    width: 100,
    align: 'center',
  },
  {
    title: '上课时间',
    key: 'day',
    editComponent: 'NInput',
    edit: true,
    width: 100,
    align: 'center',
  },
  {
    title: '座位数',
    key: 'seat',
    editComponent: 'NInput',
    edit: true,
    width: 70,
    align: 'center',
  },
  {
    title: '已选人数',
    key: 'seatChosen',
    editComponent: 'NInput',
    edit: true,
    width: 100,
    align: 'center',
  },
  {
    title: '创建日期',
    key: 'createTime',
    editComponent: 'NInput',
    edit: true,
    width: 100,
    align: 'center',
  },
  {
    title: '更新日期',
    key: 'updateTime',
    editComponent: 'NInput',
    edit: true,
    width: 100,
    align: 'center',
  },
  // {
  //   title: '是否禁用',
  //   key: 'isDeleted',
  //   editComponent: 'NSwitch',
  //   editComponentProps: {
  //     checkedValue: '0',
  //     uncheckedValue: '1',
  //   },
  //   editValueMap: (value) => {
  //     return value == '0' ? '启用' : '禁用';
  //   },
  //   edit: true,
  //   width: 100,
  //   align: 'center',
  // },
];
