version: '2'
services:
    mysql:
        network_mode: "host"
        container_name: "mysql5.7"
        environment:
            MYSQL_ROOT_PASSWORD: ""
        image: "mysql:5.7.26" 
        restart: always
        volumes:
            - "./db:/var/lib/mysql"
            - "./conf/my.cnf:/etc/my.cnf"
