stages:
  - build
  - deploy
  - clean

build-job:
  stage: build
  tags:
    - local
  script:
    - echo "Maven building..."
    - mvn clean install -DskipTests
    - echo "Build complete!"

deploy-job:
  stage: deploy
  only:
    - dev
  tags:
    - local
  script:
    - echo "Deploy running..."
    - sh /root/coesplus/shell.sh
    - echo "Deploy complete!"

clean-job:
  stage: clean
  tags:
    - local
  script:
    - echo "Maven cleaning..."
    - mvn clean
    - echo "Clean complete."
    - echo "All stages complete!"
